version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -r deployment_package.zip *

  post_build:
    commands:
      - aws lambda update-function-code --function-name backend --zip-file fileb://deployment_package.zip



